[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
NIXPACKS_NODE_VERSION = "18"

[phases.setup]
nixPkgs = ["python311", "nodejs-18_x", "npm"]

[phases.install]
cmds = [
    "cd backend && pip install -r requirements.txt",
    "npm install",
    "npm run build"
]

[phases.build]
cmds = [
    "cd backend && python manage.py collectstatic --noinput"
]

[start]
cmd = "cd backend && gunicorn sweetbite_backend.wsgi:application --bind 0.0.0.0:$PORT"

